title: Binadrish Blog
author: Adrian Galvan R.
description: Mi portafolio y blog
theme: null
baseurl: "" 
url: "https://binadrish.github.io" # URL de tu sitio
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
