title: Binadrish Blog
author: Adrian Galvan R.
description: Mi portafolio y blog
theme: minima
baseurl: "" # O el subdirectorio donde está el sitio, si aplica
url: "https://binadrish.github.io" # URL de tu sitio
permalink: /:title/